### ISSUE TITLE
Warning message during eslint-config-hapi with yarn

### ISSUE THREAD

**Issue by sitrakay** [continuationlabs/eslint-config-hapi#48] opened 2017-03-26 12:55 UTC
warning "eslint-config-hapi@10.0.0" has unmet peer dependency "eslint-plugin-hapi@4.x.x".
```bash
$ yarn add jest -D jest eslint eslint-config-hapi eslint-plugin-hapi
yarn add v0.21.3
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning "eslint-config-hapi@10.0.0" has unmet peer dependency "eslint-plugin-hapi@4.x.x".
[4/4] Building fresh packages...
```

**Comment by cjihrig** [comment] 2017-03-26 13:05
I haven't tried this, but does it make a difference if you list `eslint-plugin-hapi` before `eslint-config-hapi` in your install list? Either way, I'm going to close this as not a bug.

**Closed by cjihrig** 2017-03-26 13:05 UTC

**Comment by sitrakay** [comment] 2017-03-26 15:31
This output the same warning even if I put the `eslint-plugin-hapi` before `eslint-config-hapi`.

**Comment by cjihrig** [comment] 2017-03-26 15:44
If there is a simple fix, I'll take a PR.

**Comment by sitrakay** [comment] 2017-03-26 16:09
I just ran `$ yarn` and it doesn't displays any warning.

Thank you!
